2019-02-07 11:52:48:     Reconnected successfully!
2019-02-07 11:52:49:     Game type = "Red bonus tile" : True, "Open tanyao" : True, "Game  length" : tonpusen
2019-02-07 11:52:50:     Reconnected. Resuming game state...
2019-02-07 11:52:51:     --------------------------------------------------
2019-02-07 11:52:51:  
2019-02-07 11:52:51: 
2019-02-07 11:52:54: 
2019-02-07 11:52:54:     Remaining tiles: 67
2019-02-07 11:52:54:     --------------------------------------------------
2019-02-07 11:52:54: 
2019-02-07 11:52:55:     [Player 1] draws a tile...
2019-02-07 11:52:59:     [Player 2] draws a tile...
2019-02-07 11:53:01:     [Player 3] draws a tile...
2019-02-07 11:53:04: 
2019-02-07 11:53:07: 
2019-02-07 11:53:07:     Remaining tiles: 63
2019-02-07 11:53:07:     --------------------------------------------------
2019-02-07 11:53:07: 
2019-02-07 11:53:07:     [Player 1] draws a tile...
2019-02-07 11:53:09:     [Player 2] draws a tile...
2019-02-07 11:53:13:     [Player 3] draws a tile...
2019-02-07 11:53:19: 
2019-02-07 11:53:22: 
2019-02-07 11:53:22:     Remaining tiles: 59
2019-02-07 11:53:22:     --------------------------------------------------
2019-02-07 11:53:22: 
2019-02-07 11:53:22:     [Player 1] draws a tile...
2019-02-07 11:53:27:     [Player 2] draws a tile...
2019-02-07 11:53:28:     [Player 3] draws a tile...
2019-02-07 11:53:31: 
2019-02-07 11:53:34: 
2019-02-07 11:53:34:     Remaining tiles: 55
2019-02-07 11:53:34:     --------------------------------------------------
2019-02-07 11:53:34: 
2019-02-07 11:53:34:     [Player 1] draws a tile...
2019-02-07 11:53:37:     [Player 2] draws a tile...
2019-02-07 11:53:42:     [Player 3] draws a tile...
2019-02-07 11:53:44: 
2019-02-07 11:53:46: 
2019-02-07 11:53:46:     Remaining tiles: 51
2019-02-07 11:53:46:     --------------------------------------------------
2019-02-07 11:53:46: 
2019-02-07 11:53:47:     [Player 1] draws a tile...
2019-02-07 11:53:48:     [Player 2] draws a tile...
2019-02-07 11:53:54:     [Player 3] draws a tile...
2019-02-07 11:53:57: 
2019-02-07 11:53:58: 
2019-02-07 11:53:58:     Remaining tiles: 47
2019-02-07 11:53:58:     --------------------------------------------------
2019-02-07 11:53:58: 
2019-02-07 11:54:00:     [Player 1] draws a tile...
2019-02-07 11:54:02:     [Player 2] draws a tile...
2019-02-07 11:54:04:     [Player 3] draws a tile...
2019-02-07 11:54:06: 
2019-02-07 11:54:08: 
2019-02-07 11:54:08:     Remaining tiles: 43
2019-02-07 11:54:08:     --------------------------------------------------
2019-02-07 11:54:08: 
2019-02-07 11:54:09:     [Player 1] draws a tile...
2019-02-07 11:54:10: 
2019-02-07 11:54:12:     [Player 2] draws a tile...
2019-02-07 11:54:17:     [Player 3] draws a tile...
2019-02-07 11:54:27: 
2019-02-07 11:54:30: 
2019-02-07 11:54:30:     Remaining tiles: 39
2019-02-07 11:54:30:     --------------------------------------------------
2019-02-07 11:54:30: 
2019-02-07 11:54:30:     [Player 1] draws a tile...
2019-02-07 11:54:31:     [Player 2] draws a tile...
2019-02-07 11:54:40:     --------------------------------------------------
2019-02-07 11:54:40: 
2019-02-07 11:54:40:     <AGARI ba="1,2" hai="3,6,8,18,20,25,34,35,41,45,51,93,99,101" machi="18" ten="30,7700,0" yaku="1,1,7,1,52,1,53,1" doraHai="96" doraHaiUra="0" who="1" fromWho="2" sc="240,0,227,100,253,-80,260,0" />
2019-02-07 11:54:40: Unexpected exception
Traceback (most recent call last):
  File "c:\Users\j4903\Documents\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "c:\Users\j4903\Documents\MahjongAI\client\tenhou_client.py", line 146, in start_game
    '<AGARI' in msg and self._handle_round_end(msg)
  File "c:\Users\j4903\Documents\MahjongAI\client\tenhou_client.py", line 404, in _handle_round_end
    self._round_end_info_to_file(res_str)
  File "c:\Users\j4903\Documents\MahjongAI\client\tenhou_client.py", line 748, in _round_end_info_to_file
    self.logger_obj.add_round_end_result(msg)
  File "c:\Users\j4903\Documents\MahjongAI\logger\logger_handler.py", line 57, in add_round_end_result
    open(self.scores_path, 'a').write(msg)
  File "C:\Users\j4903\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f00b' in position 87: character maps to <undefined>
2019-02-07 11:54:40: End the game...
2019-02-07 11:54:40:     Game was ended unexpected
2019-02-07 11:54:40: 
